services:
    postgres_api_games:
        image: postgres
        container_name: postgres_api_games
        environment:
            POSTGRES_PASSWORD: "postgres"
        ports:
            - "5432:5432"
        volumes:
            - postgres_api_games:/var/lib/postgresql
        networks:
            - network_nerdapi

networks:
    network_nerdapi:
        driver: bridge

volumes:
    postgres_api_games:
        driver: local
