POST http://localhost:3000/check-user-auth-token
content-type: application/json
Authorization: Bearer eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0.BDzTmxF78Va_2hYtKyWw9sMYpsFRstUYau7LyO0vI9WTullRY8sH9CfcIRuAUVY0Mm7GdeISkX6oYPBt8XXUJdJBvFELj4rrOM4KRTAPiig36rWsjbjXQD_8hG7PMMLfAINt982IAQU_WGsN2qbpC_gJqayoZHpxsnqRqI7Z6H9XamivDNzLIdajg8Ka-Syzh2FSp5-y6tSvxaqK_pGPP0QBhqLOnwxFJBqCNz7RG_Qbu4bqiuZZENHSCOLXqJ4Pq27mw5DDTviG9Up6lZAZE337xz4nKaAW9xfitCpJcDLUsUVoaPOFWAOppeNvfAu9HvZHvk46gApWly-ExyDKVA.YsmIKb4plMMvbE8_.uqcLCGYlxi_dvoP01DphQg6DXy7PPOK47OzytOi7HSmkV1pxZNtNoXcOO-fd6V8-40Nn8z1x0NBRTCMtXUjWCWcAcpG83cWCIs5PlaOR4q4.1s-MA6MVycxD6bHVFq7LHQ
