POST http://localhost:3000/check-user-auth-token
content-type: application/json
Authorization: Bearer eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0.XnTgazPMWSI1AYM1uUGnVOdQOKiKf5_JPNtC0qVuw79Wo7o32pImRefV7WgkUjjpFyZVnKFIp0kEDoqUuNVQulQAUEDlE5IkBwh6WEYqS8p9if7HGoSTRWid6_1ExO6Sgxm1OCttbFgfqdOgHe9bbldBV2CKvqgdbGi_7vIVLpRtZddy-HfvKukXnBLPK1__4jDHjg2oFyYzjqPaoVH6YhXP6yyLn0vxwo_IzS_mpkvr-i3Fv7zvl7ogyKyCnXgEYHHa-691exjR7kzqYWMpFORstPPcOuCxmZLPIT6iwDXjYGKfPh-lANetmGpx8QyT9xGqh4sIYyUI8UcASjOutg.Y9Dtw1sAfBCCglBJ.8y23x7UT7slXTlhUHTlAJ8gxeYHlkTm9LIZpXivGc_E4rF3oxMPYTQYKBM1Qj7HGw9_eQq4xIctC-TPxexueTTwPPFv_KnP1qn3I1sAxcDsRPbiic2KcK4BzZ8dudep4CKZI87iPOTVy6pSKlwR0.wT2R4mjcTxkOi4ASZpR0kw
