POST http://localhost:3000/check-user-auth-token
content-type: application/json
Authorization: Bearer eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0.hb2JW_ew2m9kVyuum8Ig5di3_CeR2800U6KDxGeC4lWJT_Jomh3IzGcePaEU-7_uchOteZakGc5FAvb8yF-kC-v4Mv0mnL1t79dOFnrIjXiQfJ5ygy4li3LQH9yF34V5quvjnldiKb_aW2AlUXbKkENqbaihL1yLv0wNXN1qf2X7teyC4zixcmd-gMpCeLyV_2PMbgahUxUM28d4gMuaDWTtE9s42dQlSCs6jZGmGnKRPFABp7e4byLZTX_Yme8J5-VayQStIxDmx0eguTXTJD9HV4yVPKzYudKK62f3TzRCaZALgTovDxUuIP7mwqSf43ZwYqBMyh4Lm7DWAU4yvA.rEklvhOsjnUUKdJF.aVwAh2EGSrPEou5odmmFBlMP2oc4P-UjSr1VUWw65PID604cx8hoSuV7Ck24DgqEcDQ31nbSNvhS0dddKN63gS8AEUP1WbKnj2ortpUdoVI.-0AzV02_M8MCaiAXoOX3dA
