# PUT http://localhost:3000/profile
PUT https://api.games.alexgalhardo.com/profile
content-type: application/json
Authorization: Bearer eyJhbGciOiJSU0EtT0FFUC0yNTYiLCJlbmMiOiJBMjU2R0NNIn0.B0SxorTnEaBCT6MJwHdQ132bvxHsrmtbyIDYbGfj4zMgiK4kxShxt5JiEaTaZqLpvLRBIX6FWswmRjt7O5H8zyA9R6EqaT-a3iRaB_OLf8-lSdBhyWGkwvshOAHY5TpQ_lSSUycaQ0G_lZgGSfWKdKeGCYoFjyDm173Gv4laGS9srYy3k41DCQ0uJJOyJDf6E0POnG2kyv-XqQSINjQhw6p96zxt-x1ZlOqPbkGF7F20pozwe4n0_GNHLeRrP4iieRHNpnlJnKigAVRmBJtmR6OcyyCJRr-da1NA0zZsyhwRDr2CQ2yQ9RArCMiPtQPtrR62MHDZaoWyndVeymXQ3w.SMlXJHK3VDCFqQB0.tWdhD2HTLm9DrC0Xt4p07mqDAd8-dDw6CN3whGMSgZSxIyXNbB1ppR32dMkg5MTIyhiW4aXXDvrlI2WL0PvrLV352HpFvTKDjOq1__Z5TJM.spATIb9GYZ2l_jaUn6AsUw

{
    "name": "Vieira Alex",
    "phone_number": "5518996971457"
}
