import { z } from "zod";

export const envsLocalValidator = z.object({
	NODE_ENV: z.enum(["local"]),
	SERVER_PORT: z.number().default(3000),
	API_KEY_ADMIN: z.string(),
	USE_JSON_DATABASE: z.enum(["true", "false"]),
	LOG_PRISMA_QUERIES: z.enum(["true", "false"]),
	ENABLE_TELEGRAM_LOGS: z.enum(["true", "false"]),
	APP_FRONT_URL_DEV: z.string(),
	APP_FRONT_URL_PROD: z.string(),
	JWT_SECRET: z.string(),
	TELEGRAM_BOT_HTTP_TOKEN: z.string(),
	TELEGRAM_BOT_CHANNEL_ID: z.string(),
	SMTP_HOST: z.string(),
	SMTP_PORT: z.string(),
	SMTP_USER: z.string().optional(),
	SMTP_PASSWORD: z.string().optional(),
	SMTP_EMAIL_FROM: z.string(),
	LOCALE_DATE_TIME: z.string().default("pt-BR"),
	DATABASE_URL: z.string().default("postgres://postgres:postgres@localhost:5432/postgres_nerdapi?schema=public"),
	DATABASE_HOST: z.string(),
	DATABASE_USERNAME: z.string(),
	DATABASE_PASSWORD: z.string(),
	DATABASE_NAME: z.string(),
	STRIPE_SK_TEST: z.string(),
	GOOGLE_CLIENT_ID: z.string(),
	GOOGLE_CLIENT_SECRET: z.string(),
	GITHUB_CLIENT_ID: z.string(),
	GITHUB_CLIENT_SECRET: z.string(),
	NOOB_API_REQUESTS_PER_DAY: z.number().default(20),
	CASUAL_API_REQUESTS_PER_DAY: z.number().default(500),
	PRO_API_REQUESTS_PER_DAY: z.number().default(2000),
});
